# Kitty loads this from ~/.config/kitty/kitty.conf
# See https://sw.kovidgoyal.net/kitty/conf/#
# Tip:
# - config reload: ctrl+shift+f5
# - loading docs in the browser: ctrl+shift+f1
# - edit config: ctrl+shift+f2

include ./themes/catppuccin-mocha.conf

# Shortcuts to disable so that they are not blocked from reaching tmux.
# We are ok with this as we atm use kitty for other reasons that those
# shortcuts.
# See https://sw.kovidgoyal.net/kitty/overview and
# https://sw.kovidgoyal.net/kitty/actions/#action-no_op .
map ctrl+shift+left no_op
map ctrl+shift+right no_op
