# Some basic things
unbind C-b
set -g prefix C-a
bind r source-file ~/.tmux.conf
set -g base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"
set -g allow-rename off

set -g mode-keys vi

# Moving between windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# Moving windows around (windows order)
bind -n M-S-Left swap-window -t -1 \; previous-window
bind -n M-S-Right swap-window -t +1 \; next-window

# Moving between panes with arrow keys
bind -n C-S-Left select-pane -L
bind -n C-S-Right select-pane -R
bind -n C-S-Up select-pane -U
bind -n C-S-Down select-pane -D

# Splitting windows - keeping original CWD + using current CWD (by adding a
# shift key)
bind '-' split-window -v
bind '_' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h
bind '|' split-window -h -c "#{pane_current_path}"


# Status bar
set -g status-style bg=default,fg=white
set -g status-justify left
set -g status-left '#S  '
set -g status-left-length 30
set -g status-left-style fg=white
set -g status-right ''
set -g window-status-separator " "
set -g window-status-style fg=white,bg=#313244
set -g window-status-format " #I: #W#F "

# color experiment
set -g window-status-current-style fg='#1e1e2e',bg='#f38ba8',bold
set -g window-status-current-format " #I: #W#F "

# last window styling window
set -g window-status-last-style bg=#313244,fg=#f38ba8

# Sessions list
set -g mode-style fg=white,bg='#d40457',bold

# new window keeping CWD
bind C new-window -c "#{pane_current_path}"

# longer error message display
set-option -g display-time 3000


##############################################################################
# Support for nesting (see #tmux-nesting)
##############################################################################

bind -T root M-Up  \
  set prefix None \;\
  set key-table off \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S \;\
  set window-status-current-style fg=white,bg=blue \;\
  set window-status-current-format "[\^\^\^ #W \^\^\^]"


bind -T off M-down \
  set -u prefix \;\
  set -u key-table \;\
  set -u window-status-current-style \;\
  set -u window-status-current-format \;\
  refresh-client -S \;\


##############################################################################
# Make `s` use session switcher based on fzf,
##############################################################################

# Rebind the original switcher to `S`.
# Note: `-s` param to choose-tree makes it look like default `s` switcher
# (with collapsed sessions) -- c.f. man tmux.
bind S choose-tree -s

# Finally, bind fzf based to `s`
# Usage of `--tmux` causes fzf to display itself on tmux floating window.
# Note: We use double `##` form to escape `#` for the config loading step,
# otherwise whatever evaluates from, say, `#I`, would be put into shell
# command as const value.
unbind s

# Variant with default sorting - alphabetically by name
# bind-key s run-shell 'sname="$(tmux list-sessions -F "##S" | fzf --tmux top --layout reverse)"; if [ "$sname" != "" ]; then tmux switch -t "$sname"; fi'

# Variant with sorting by last use
bind-key s run-shell 'sname="$(tmux list-sessions -F "##S ##{session_activity}" | sort -k 2 -r | awk "{ print \$1 }" | fzf --tmux top --layout reverse)"; if [ "$sname" != "" ]; then tmux switch -t "$sname"; fi'


##############################################################################
# Make `w` use window switcher based on fzf.
##############################################################################

# Rebind the original switcher to W
bind W choose-window

# Note: we use `cut` not `awk` due to some problems with escaping with awk
# here...
unbind w
bind-key w run-shell 'line="$(tmux list-windows -F "##I ##W" | fzf --tmux top --layout reverse)"; if [ "$line" != "" ]; then wid="$(echo "$line" | cut -d" " -f1)";  tmux select-window -t "$wid"; fi'
